In [59]:
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np

In [60]:
import sklearn as sk

In [13]:


import pandas as pd

# Load the Excel file properly
df = pd.read_excel(r"C:\Users\saksham verma\Desktop\1750577562424-iris-train.xlsx", engine='openpyxl')

# View the data
df.head()

   sepallength  sepalwidth  petallength  petalwidth           class
0          7.9         3.8          6.4         2.0  Iris-virginica
1          7.7         3.8          6.7         2.2  Iris-virginica
2          7.7         3.0          6.1         2.3  Iris-virginica
3          7.7         2.8          6.7         2.0  Iris-virginica
4          7.7         2.6          6.9         2.3  Iris-virginica

In [14]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [15]:
X = df.iloc[:, :-1]  # All columns except the last as features
y = df.iloc[:, -1]   # Last column as label

In [25]:
X

     sepallength  sepalwidth  petallength  petalwidth
0            7.9         3.8          6.4         2.0
1            7.7         3.8          6.7         2.2
2            7.7         3.0          6.1         2.3
3            7.7         2.8          6.7         2.0
4            7.7         2.6          6.9         2.3
..           ...         ...          ...         ...
111          4.5         2.3          1.3         0.3
112          4.4         3.2          1.3         0.2
113          4.4         3.0          1.3         0.2
114          4.4         2.9          1.4         0.2
115          4.3         3.0          1.1         0.1

[116 rows x 4 columns]

In [16]:
model = RandomForestClassifier()
model.fit(X, y)

RandomForestClassifier()

In [17]:
predictions = model.predict(X)  # Predict on the same/new data (for demonstration)
print(predictions)  # Display predictions

['Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa']

In [34]:
from sklearn.ensemble import RandomForestClassifier
df.head(10)

   sepallength  sepalwidth  petallength  petalwidth           class
0          7.9         3.8          6.4         2.0  Iris-virginica
1          7.7         3.8          6.7         2.2  Iris-virginica
2          7.7         3.0          6.1         2.3  Iris-virginica
3          7.7         2.8          6.7         2.0  Iris-virginica
4          7.7         2.6          6.9         2.3  Iris-virginica
5          7.6         3.0          6.6         2.1  Iris-virginica
6          7.4         2.8          6.1         1.9  Iris-virginica
7          7.3         2.9          6.3         1.8  Iris-virginica
8          7.2         3.6          6.1         2.5  Iris-virginica
9          7.2         3.2          6.0         1.8  Iris-virginica

In [40]:
data=df.iloc[: , : -1]

In [50]:
values=df[["class"]]

In [51]:
data

     sepallength  sepalwidth  petallength  petalwidth
0            7.9         3.8          6.4         2.0
1            7.7         3.8          6.7         2.2
2            7.7         3.0          6.1         2.3
3            7.7         2.8          6.7         2.0
4            7.7         2.6          6.9         2.3
..           ...         ...          ...         ...
111          4.5         2.3          1.3         0.3
112          4.4         3.2          1.3         0.2
113          4.4         3.0          1.3         0.2
114          4.4         2.9          1.4         0.2
115          4.3         3.0          1.1         0.1

[116 rows x 4 columns]

In [52]:
values

              class
0    Iris-virginica
1    Iris-virginica
2    Iris-virginica
3    Iris-virginica
4    Iris-virginica
..              ...
111     Iris-setosa
112     Iris-setosa
113     Iris-setosa
114     Iris-setosa
115     Iris-setosa

[116 rows x 1 columns]

In [55]:

model = RandomForestClassifier()
model.fit(data,values)

C:\Users\saksham verma\anaconda3\envs\booksenv\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

RandomForestClassifier()

In [65]:
df2 = pd.read_excel(r"C:\Users\saksham verma\Desktop\-iris-test (1).xlsx", engine='openpyxl')

In [66]:
df2.head()

   sepallength  sepalwidth  petallength  petalwidth            class
0          5.4         3.0          4.5         1.5  Iris-versicolor
1          5.3         3.7          1.5         0.2      Iris-setosa
2          5.2         4.1          1.5         0.1      Iris-setosa
3          5.2         3.5          1.5         0.2      Iris-setosa
4          5.2         3.4          1.4         0.2      Iris-setosa

In [68]:
test_data=df2.iloc[: , :-1]

In [70]:
test_data.head()

   sepallength  sepalwidth  petallength  petalwidth
0          5.4         3.0          4.5         1.5
1          5.3         3.7          1.5         0.2
2          5.2         4.1          1.5         0.1
3          5.2         3.5          1.5         0.2
4          5.2         3.4          1.4         0.2

In [77]:
test_values= df2.iloc[:, -1]
test_values.head()

0    Iris-versicolor
1        Iris-setosa
2        Iris-setosa
3        Iris-setosa
4        Iris-setosa
Name: class, dtype: object

In [82]:
result=model.predict(test_data)
print(result)

['Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa']

In [83]:
test_values= np.array(test_values)

In [84]:
test_values

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)

In [96]:
def p(test_values, result):
    correct_values = 0
    wrong = 0
    
    # zip() pairs up each actual value with its corresponding predicted value
    for actual, predicted in zip(test_values, result):
        if actual == predicted:
            print("true")
            correct_values += 1
        else:
            print("false")
            wrong += 1
            
    print(f"\nTotal Correct: {correct_values}")
    print(f"Total Wrong: {wrong}")
    
    return correct_values, wrong

In [98]:
p(test_values,result)

true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
false
true
true
true
true

Total Correct: 33
Total Wrong: 1

(33, 1)

In [ ]:

predictions = model.predict(z)  
print(predictions)